sqldb:
  qa_connection_string: 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=dubnium\testsql16;DATABASE=qa_PanelRiderDB;UID=testdbuser;PWD=111111;'
  dev_connection_string: 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=betelgeuse01,50201;DATABASE=PanelRiderDB;Trusted_Connection=yes;'
pr:
  login: admin@expertnoemnenie.ru
  passwd: 111111
  qa_url: http://qa.panelrider.com/
  dev_url: https://cp.dev-pr.panelrider.com/
  project_url: admin/projects/
  project_id: 765277185
  c_template_id: 768398738
  headers:
    accept: application/json
    content_type: application/json
  default_settings_json: {  "Id": 765277185,  "Categories": [    {      "Id": 842,      "Description": null,      "Name": null,      "SortOrder": 0,      "Updated": "0001-01-01T00:00:00"    }  ],  "ClientStaffId": null,  "Collectors": [],  "DeadlineDT": null,  "Deleted": false,  "Descriptions": {    "Comparer": {},    "Count": 0,    "Keys": [],    "Values": []  },  "EstimatedIR": null,  "ExternalId": null,  "FieldCloseDT": null,  "InnerName": "S-765277185",  "IsSetup": false,  "LastSurveyAction": null,  "LastSyncDT": null,  "LastSyncStatus": 0,  "LengthOfInterview": 10,  "ManagerId": 5129884,  "ManagerNiceName": "Админ",  "Name": "Новый опрос",  "Notes": null,  "PartnerClientId": null,  "PartnerId": 1029693,  "PlannedCompleteCount": 0,  "PlannedIR": 0,  "ProjectManagerId": 5129884,  "ProjectManagerNiceName": "Админ",  "ReminderFrequency": null,  "RequestCondition": {    "ConditionType": 0,    "Request": "{\r\n  \"DataPoints\": [\r\n    {\r\n      \"DataPoint\": 100019,\r\n      \"Type\": \"Exclude\",\r\n      \"Unknown\": \"Include\",\r\n      \"Values\": [\r\n        9,\r\n        100\r\n      ]\r\n    }\r\n  ]\r\n}",    "RequestError": null  },  "Settings": {    "AllowedDeviceTypes": 0,    "BrandPulseType": 1,    "CheckCookie": false,    "CPICurrencySymbol": null,    "CPIValue": null,    "CustomSettings": null,    "IsBrandPulse": false,    "LastTemplateId": 768398738,    "Overhead": null,    "ShowCaptcha": 1,    "ShowTheme": true,    "SurveyDescription": null,    "SurveyEngineAdminURl": null,    "TechnicalRequirements": 0,    "СonditionalLinks": [],    "DirectorySEId": 768457738  },  "State": 4,  "StatusSynchronization": false,  "StudyType": 0,  "SurveyEngineAdminURl": null,  "SurveyEngineQuotaUrl": null,  "SurveyEngineTemplateUrl": "http://hub.opinion.team/Request?bfsrptid={panel}&rid={token}&token={id}&uid={user}&crid={PROJECTID}",  "SurveyEngineTestUrl": null,  "SurveyProvider": "PanelRider",  "TotalCollectors": 0,  "Updated": "2021-07-28T14:00:05.059112",  "UseMultilinks": false}
  default_settings:
    url_template: https://hub.dev-pr.panelrider.com//Request?bfsrptid={panel}&rid={token}&token={id}&uid={user}&crid={PROJECTID}
    manager: Админ
    project_manager: Админ
    device_type_text: Все устройства
    device_type_show_text: Наследовать от типа устройств
  default_c_template_settings_json: {"AllowDuplicates":false,"AutoFill":0,"Deleted":false,"ErrorMessage":null,"Id":768398738,"InvitationTemplate":0,"IsValid":true,"Name":"test_template","PanelId":1029695,"PanelName":"Экспертное мнение","ParsedString":null,"ReminderTemplate":0,"ShowCaptcha":0,"SurveyId":765277185,"SurveyName":"тестовый проект для тестирования тестов","SurveyRewards":"{\"91\":20}","SurveyState":4,"ValidationType":0}
  default_c_template_settings:
    panel: Экспертное мнение
    invitation: По-умолчанию
    reminder: По-умолчанию
    autofill: Нет
    captcha: Наследовать
  wait_time: 5
  xpctd_settings:
    url_template: https://qasawtooth.opinion.team/projects04/TestSurveyQA/cgi-bin/ciwweb.pl?studyname=TestSurveyQA&bfrid={token}
    inner_name: тестовый проект для тестирования тестов
    name: тесты тесты
    type: Ad-hoc
    description: some nice description text
    note: some annoying comments
    device_type_text: Только ПК
    device_type_show_text: Только мобильные
    manager: Бот
    project_manager: Бот
    category: Безалкогольные напитки
  xpctd_c_tmplt_settings:
    name: new badass name
    panel: BigPoll
    invitation: Приглашение на опрос без мобильного
    reminder: Повторное приглашение на опрос ребенка 15 - 17 лет
    autofill: Да
    captcha: Да
    reward: 40
