sqldb:
  host: dubnium\testsql16
  db: qa_PanelRiderDB
  user: testdbuser
  passwd: 111111
pr:
  login: admin@expertnoemnenie.ru
  passwd: 111111
  url: http://qa.panelrider.com/
  project_url: http://qa.panelrider.com/admin/projects/765277185
  project_id: 765277185
  c_template_id: 768398738
  headers:
    accept: application/json
    content_type: application/json
  default_settings_json: {"Id":765277185,"PartnerClientId":null,"PartnerId":1029693,"ClientStaffId":null,"Name":"Новый опрос","EstimatedIR":null,"FieldCloseDT":null,"ReminderFrequency":null,"ProjectManagerId":5129884,"ProjectManagerNiceName":"Админ","ManagerId":5129884,"ManagerNiceName":"Админ","InnerName":"S-765277185","SurveyProvider":"PanelRider","ExternalId":null,"Descriptions":{"Comparer":{},"Count":0,"Keys":[],"Values":[]},"State":2,"IsSetup":false,"StudyType":0,"SurveyEngineTemplateUrl":null,"SurveyEngineTestUrl":null,"UseMultilinks":false,"SurveyEngineQuotaUrl":null,"PlannedIR":0,"PlannedCompleteCount":0,"DeadlineDT":null,"Notes":null,"Settings":{"CPICurrencySymbol":"₽","ShowTheme":true,"BrandPulseType":1,"IsBrandPulse":false,"HashSecret":"Naturwissenschaftler","SurveyEngineAdminURl":null,"SurveyDescription":null,"ShowCaptcha":1,"TechnicalRequirements":0,"AllowedDeviceTypes":0,"CPIValue":null,"Overhead":null,"CustomSettings":null},"Updated":"2021-01-15T13:20:50.9336278","Deleted":false,"LengthOfInterview":10,"Categories":[{"Id":842,"Name":null,"Description":null,"SortOrder":0,"Updated":"0001-01-01T00:00:00"}],"Collectors":[],"TotalCollectors":0,"RequestCondition":{"ConditionType":0,"Request":"{\r\n  \"DataPoints\": [\r\n    {\r\n      \"DataPoint\": 100019,\r\n      \"Type\": \"Exclude\",\r\n      \"Unknown\": \"Include\",\r\n      \"Values\": [\r\n        9,\r\n        100\r\n      ]\r\n    }\r\n  ]\r\n}","RequestError":null},"SurveyEngineAdminURl":null,"IsHidden":true,"StatusSynchronization":false,"LastSurveyAction":null,"LastSyncStatus":0,"LastSyncDT":null}
  default_settings:
    url_template: http://hub.opinion.team/Request?bfsrptid={panel}&rid={token}&token={id}&uid={user}&crid=
    manager: Админ
    project_manager: Админ
    device_type_text: Все устройства
    device_type_show_text: Наследовать от типа устройств
  default_c_template_settings_json: {"AllowDuplicates":false,"AutoFill":0,"Deleted":false,"ErrorMessage":null,"Id":768398738,"InvitationTemplate":0,"IsValid":true,"Name":"test_template","PanelId":1029695,"PanelName":"Экспертное мнение","ParsedString":null,"ReminderTemplate":0,"ShowCaptcha":0,"SurveyId":765277185,"SurveyName":"тестовый проект для тестирования тестов","SurveyRewards":"{\"91\":20}","SurveyState":4,"ValidationType":0}
  default_c_template_settings:
    panel: Экспертное мнение
    invitation: По-умолчанию
    reminder: По-умолчанию
    autofill: Нет
    captcha: Наследовать
  wait_time: 5
  xpctd_settings:
    url_template: https://qasawtooth.opinion.team/projects04/TestSurveyQA/cgi-bin/ciwweb.pl?studyname=TestSurveyQA&bfrid={token}
    inner_name: тестовый проект для тестирования тестов
    name: тесты тесты
    type: Ad-hoc
    description: some nice description text
    note: some annoying comments
    device_type_text: Только ПК
    device_type_show_text: Только мобильные
    manager: Бот
    project_manager: Бот
    category: Безалкогольные напитки
  xpctd_c_tmplt_settings:
    name: new badass name
    panel: BigPoll
    invitation: Приглашение на опрос без мобильного
    reminder: Повторное приглашение на опрос ребенка 15 - 17 лет
    autofill: Да
    captcha: Да
